/*
 * Copyright (c) 2024 Gaksy (Fuhongren)
 *
 * This work is licensed under the GNU Lesser General Public License v3.0.
 * You may obtain a copy of the license at https://www.gnu.org/licenses/lgpl-3.0.html.
 *
 * This source code form is subject to the terms of the LGPL v3.0 license.
 * If a copy of the LGPL was not distributed with this file, you can obtain one
 * at the above license URL.
 */

/*
 * Author: Gaksy
 * Date Created: 09/20/2026
 */

#ifndef GALIB_MINECRAFT_BLOCKSTATEMAP_H
#define GALIB_MINECRAFT_BLOCKSTATEMAP_H

#include <cstddef>
#include <map>
#include <string>

#include "GalibNamespaceDef.h"

namespace galib::minecraft {

// Block names differ between Minecraft 1.12.2 and 1.20:
//
//   1.12.2   "minecraft:wool:5"            (namespace:name:metadata)
//   1.20     "minecraft:lime_wool"         (flattened name + block states)
//   1.20     "minecraft:oak_log[axis=y]"   (block states in brackets)
//
// LittleTiles ships the translation table it uses itself when it loads a 1.12.2
// structure ("1.12.2.txt" inside the mod jar, read by
// OldLittleTilesDataParser in the 1.20 sources), and this class is that table:
// the entries are embedded in BlockStateMapData.cpp, generated by
// tools/gen_block_state_map.py.
//
// Coverage is deliberately the same as the mod's: every vanilla block that
// existed in 1.12.2 plus LittleTiles' own blocks. Other mods' blocks are not in
// it - for those the converter falls back to LittleTiles' own heuristic (drop
// the metadata / block states, keep the base name) and reports it, because only
// the game knows whether the mod's block still exists under that name.
class BlockStateMap {
 public:
  // The process-wide table. Construction is cheap (a few hundred entries) and
  // happens on first use.
  [[nodiscard]] static const BlockStateMap& Instance();

  [[nodiscard]] std::size_t size() const { return legacy_to_modern_.size(); }
  [[nodiscard]] bool empty() const { return legacy_to_modern_.empty(); }

  // "minecraft:wool:5" -> "minecraft:lime_wool".
  // Returns the input unchanged when the name is not in the table;
  // *p_desc_mapped (when given) tells the caller which of the two happened.
  [[nodiscard]] std::string ToModern(const std::string& kLegacyName,
                                     bool* p_desc_mapped = nullptr) const;

  // "minecraft:oak_log[axis=y]" -> "minecraft:log:4" (the reverse entry).
  // A 1.20 name that has no 1.12.2 counterpart is returned without its block
  // states ("minecraft:calcite[axis=x]" -> "minecraft:calcite"), which is what
  // LittleTiles' own converter does when it cannot resolve a name.
  [[nodiscard]] std::string ToLegacy(const std::string& kModernState,
                                     bool* p_desc_mapped = nullptr) const;

 private:
  BlockStateMap();

  std::map<std::string, std::string> legacy_to_modern_;
  std::map<std::string, std::string> modern_to_legacy_;
};

// The embedded table (see BlockStateMapData.cpp, generated by
// tools/gen_block_state_map.py); entry i maps LegacyNames()[i] to ModernStates()[i].
namespace block_map_data {

[[nodiscard]] const char* const* LegacyNames();
[[nodiscard]] const char* const* ModernStates();
[[nodiscard]] std::size_t Count();

}  // namespace block_map_data

// Strip the block-state part of a 1.20 block name: "minecraft:oak_log[axis=y]"
// -> "minecraft:oak_log". Names without block states are returned unchanged.
[[nodiscard]] std::string StripBlockStates(const std::string& kName);

}  // namespace galib::minecraft

#endif  // GALIB_MINECRAFT_BLOCKSTATEMAP_H
