#!/usr/bin/env python3
"""Regenerate Galib/Minecraft/BlockStateMapData.cpp.

LittleTiles ships the "old block id -> flattened block state" table that it uses
itself when it loads a 1.12.2 structure (see LittleTiles 1.20's
OldLittleTilesDataParser). The table lives in the mod jar as the resource file
``1.12.2.txt`` and holds one entry per line:

    minecraft:wool:5<SECTION SIGN>minecraft:lime_wool

This project embeds a copy of that table so that converting a structure between
the 1.12.2 and the 1.20 SNBT dialect works head-less, without the game or the
mod. LittleTiles is LGPL-3.0, the same license as this project; see
docs/licensing-summary.md for the attribution.

Usage:
    python tools/gen_block_state_map.py <path to LittleTiles' 1.12.2.txt>
    python tools/gen_block_state_map.py --from-repo <LittleTiles checkout>
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import subprocess
import sys

SEPARATOR = "\u00a7"
REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "Galib" / "Minecraft" / "BlockStateMapData.cpp"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "table",
        nargs="?",
        help="path of LittleTiles' 1.12.2.txt",
    )
    parser.add_argument(
        "--from-repo",
        help="path of a LittleTiles checkout (its 1.20 branch); "
        "src/main/resources/1.12.2.txt is used",
    )
    return parser.parse_args()


def resolve_table(args: argparse.Namespace) -> pathlib.Path:
    if args.from_repo:
        return pathlib.Path(args.from_repo) / "src" / "main" / "resources" / "1.12.2.txt"
    if args.table:
        return pathlib.Path(args.table)
    raise SystemExit("give the path of LittleTiles' 1.12.2.txt (or --from-repo)")


def git_revision(table: pathlib.Path) -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(table.parent), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def read_entries(table: pathlib.Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()
    for number, line in enumerate(table.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        parts = line.split(SEPARATOR)
        if len(parts) != 2:
            raise SystemExit(f"{table}:{number}: expected exactly one separator")
        legacy, modern = parts[0].strip(), parts[1].strip()
        if legacy in seen:
            raise SystemExit(f"{table}:{number}: duplicate key {legacy}")
        seen.add(legacy)
        entries.append((legacy, modern))
    return entries


def escape(text: str) -> str:
    if not text.isascii():
        raise SystemExit(f"non-ASCII entry: {text!r}")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(entries: list[tuple[str, str]], revision: str) -> str:
    today = datetime.date.today().isoformat()
    lines = [
        "/*",
        " * Copyright (c) 2024 Gaksy (Fuhongren)",
        " *",
        " * This work is licensed under the GNU Lesser General Public License v3.0.",
        " * You may obtain a copy of the license at https://www.gnu.org/licenses/lgpl-3.0.html.",
        " *",
        " * This source code form is subject to the terms of the LGPL v3.0 license.",
        " * If a copy of the LGPL was not distributed with this file, you can obtain one",
        " * at the above license URL.",
        " */",
        "",
        "/*",
        " * Generated by tools/gen_block_state_map.py - do not edit by hand.",
        f" * Generated on {today} from LittleTiles' src/main/resources/1.12.2.txt",
        f" * (branch 1.20, revision {revision}).",
        " *",
        " * The table is LittleTiles' own 1.12.2 -> 1.20 block mapping (LGPL-3.0, the same",
        " * license as this project); it is what the mod itself uses when it loads an old",
        " * structure. Entry i maps kLegacyNames[i] to kModernStates[i].",
        " */",
        "",
        '#include "Minecraft/BlockStateMap.h"',
        "",
        "namespace galib::minecraft::block_map_data {",
        "",
        "namespace {",
        "",
        "const char* const kLegacyNames[] = {",
    ]
    lines += [f"    {escape(legacy)}," for legacy, _ in entries]
    lines += [
        "};",
        "",
        "const char* const kModernStates[] = {",
    ]
    lines += [f"    {escape(modern)}," for _, modern in entries]
    lines += [
        "};",
        "",
        "}  // namespace",
        "",
        "const char* const* LegacyNames() { return kLegacyNames; }",
        "",
        "const char* const* ModernStates() { return kModernStates; }",
        "",
        "std::size_t Count() { return sizeof(kLegacyNames) / sizeof(kLegacyNames[0]); }",
        "",
        "}  // namespace galib::minecraft::block_map_data",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    table = resolve_table(args)
    if not table.is_file():
        raise SystemExit(f"not found: {table}")
    entries = read_entries(table)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render(entries, git_revision(table)))
    print(f"wrote {OUTPUT} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
